- name: Run docker container
  hosts: frontend
  become: true
  tasks:
    - name: copy a file
      copy:
        src: compose.yaml
        dest: /home/compose.yaml

    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - aptitude
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip

    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: docker-ce
        state: latest

    - name: adding ubuntu to docker group
      user:
        name: fmuyassarov
        groups: docker
        append: yes

    - name: Install Docker Modules for Python
      pip:
        name: "{{ item }}"
        state: present
      loop:
      - pyopenssl==23.2.0
      - docker
      - docker-compose

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home
        files:
        - compose.yaml
        state: present
